database:
  saleRecord:
    driver: mysql
    connection: root:root@tcp(localhost:3307)/pangpang_brand_nhub?charset=utf8&parseTime=True&loc=UTC
  order:
    driver: mysql
    connection: root:root@tcp(localhost:3307)/pangpang_brand_order?charset=utf8&parseTime=True&loc=UTC
services:
  membershipApi: https://staging.p2shop.com.cn/pangpang-brand/membership-api
serviceName: sale-record-postprocess-api