database:
  saleRecord:
    driver: mysql
    connection: pangpang_app:Eland^123@tcp(10.173.208.142:3307)/pangpang_brand_nhub?charset=utf8&parseTime=True&loc=UTC
  order:
    driver: mysql
    connection: pangpang_app:Eland^123@tcp(10.173.208.142:3307)/pangpang_brand_order?charset=utf8&parseTime=True&loc=UTC
  logger:
    kafka:
      brokers:
        - 10.173.208.142:9092
      topic: sqllog
behaviorLog:
  kafka:
    brokers:
      - 10.173.208.142:9092
    topic: behaviorlog
eventKafka:
  saleRecordEvent:
    brokers:
      - 10.173.208.142:9092
    topic: pangpang-brand-sale-record
  promotionEvent:
    brokers:
      - 10.173.208.142:9092
    topic: pangpang-brand-offer
appenv: pangpang-brand-staging
services:
  offerApi: http://offer-api.pangpang-brand-staging:5000
  promotionApi: https://dmz-staging.p2shop.com.cn/mslv2/promotion-api
  productApi: http://product-api.pangpang-brand-staging:8000
  storeApi: http://place-management-api.pangpang-brand-staging:8080
  benefitApi: http://benefit-api.pangpang-brand-staging:8000
  placeManagementApi: http://place-management-api.pangpang-brand-staging:8080
  cslCustomerApi: https://dmz-staging.p2shop.com.cn/mslv2/csl-customer-if
serviceName: sale-record-postprocess-api