database:
  saleRecord:
    driver: mysql
    connection: root:root@tcp(localhost:3306)/pangpang_brand_nhub?charset=utf8&parseTime=True&loc=UTC
  order:
    driver: mysql
    connection: root:root@tcp(localhost:3306)/pangpang_brand_order?charset=utf8&parseTime=True&loc=UTC
  mslv2Readonly:
    driver: mysql
    connection: root:root@tcp(localhost:3306)/pangpang_brand_nhub?charset=utf8&parseTime=True&loc=Local
behaviorLog:
  kafka:
    brokers:
      - localhost
    topic: behaviorlog
eventKafka:
  saleRecordEvent:
    brokers:
      - localhost:9092
    topic: pangpang-brand-sale-record
  promotionEvent:
    brokers:
      - localhost:9092
    topic: offer
services:
  offerApi: https://staging.p2shop.com.cn/pangpang-brand/offer-api
  promotionApi: https://dmz-staging.p2shop.com.cn/mslv2/promotion-api
  productApi: https://staging.p2shop.com.cn/pangpang-brand/product-api
  storeApi: https://staging.p2shop.com.cn/pangpang-brand/place-management-api
  benefitApi: https://staging.p2shop.com.cn/pangpang-brand/benefit-api
  placeManagementApi: https://staging.p2shop.com.cn/pangpang-brand/place-management-api
  cslCustomerApi: https://dmz-staging.p2shop.com.cn/mslv2/csl-customer-if
  clearanceAdapterForSaleRecordApi: https://dmz-staging.p2shop.com.cn/mslv2/clearance-adapter-for-sale-record
  memberApi: https://staging.p2shop.com.cn/pangpang-brand/member-api
  refundApprovalApi: https://staging.p2shop.com.cn/pangpang-brand/refund-approval-api
appenv: dev
serviceName: sale-record-postprocess-api