database:
  saleRecord:
    driver: mysql
    connection: pangpang_app:Eland^123@tcp(rm-uf697cmu717ius9i3.mysql.rds.aliyuncs.com)/pangpang_brand_nhub?charset=utf8
logger:
  kafka:
        brokers:
          - 10.26.205.20:9092
          - 10.27.116.104:9092
          - 10.27.121.103:9092
        topic: sqllog
behaviorLog:
    kafka:
      brokers:
          - 10.26.205.20:9092
          - 10.27.116.104:9092
          - 10.27.121.103:9092
      topic: behaviorlog
eventMessageBroker:
  kafka:
    brokers:
          - 10.26.205.20:9092
          - 10.27.116.104:9092
          - 10.27.121.103:9092
    topic: nhub-sale-record-postprocess-api
services:
  membershipApi: http://membership-api.pangpang-brand:8080