database:
  saleRecord:
    driver: mysql
    connection: pangpang_app:Eland^123@tcp(10.30.8.55:3306)/pangpang_brand_nhub?charset=utf8&parseTime=True&loc=UTC
    logger:
      kafka:
        brokers:
          - 10.30.8.55:9092
        topic: sqllog
  order:
    driver: mysql
    connection: pangpang_app:Eland^123@tcp(10.30.8.55:3306)/pangpang_brand_order?charset=utf8&parseTime=True&loc=UTC
    logger:
      kafka:
        brokers:
          - 10.30.8.55:9092
        topic: sqllog
behaviorLog:
  kafka:
    brokers:
      - 10.30.8.55:9092
    topic: behaviorlog
saleRecordEvent:
  kafka:
    publisher:
      brokers:
        - 10.30.8.55:9092
      topic: pangpang-brand-sale-record
    consumer:
      brokers:
        - 10.30.8.55:9092
      topic: pangpang-brand-offer
appenv: pangpang-brand-qa
services:
  offerApi: http://offer-api.pangpang-brand-qa:8080
  promotionApi: http://promotion-api.mslv2-qa:5000
  productApi: http://product-api.pangpang-brand-qa:8080
  storeApi: http://place-management-api.pangpang-brand-qa:8080
serviceName: sale-record-postprocess-api