database:
  saleRecord:
    driver: mysql
    connection: pangpang_app:Eland^123@tcp(10.173.208.142:3307)/pangpang_brand_nhub?charset=utf8
logger:
  kafka:
        brokers:
          - 10.173.208.142:9092
        topic: sqllog
behaviorLog:
    kafka:
      brokers:
        - 10.173.208.142:9092
      topic: behaviorlog
eventMessageBroker:
  kafka:
    brokers:
      - 10.173.208.142:9092
    topic: nhub-sale-record-postprocess-api
services:
  membershipApi: http://membership-api.pangpang-brand-staging:8080